In [92]:
import pandas as pd


cpi_data = pd.read_csv(r"data\historical_data_with_variables.csv", skiprows = 3)
epi14_data = pd.read_csv(r"data\2014-epi-scores.csv")
epi16_data = pd.read_csv(r"data\2016-epi-scores.csv")
epi18_data = pd.read_csv(r"data\2018-epi-scores.csv")
epi20_data = pd.read_csv(r"data\2020-epi-scores.csv")
epi22_data = pd.read_csv(r"data\2022-epi-scores.csv")
epi24_data = pd.read_csv(r"data\2024-epi-scores.csv")

In [93]:
cpi_data.head()

,Country / Territory,ISO3,Year,Region,CPI score,Rank,Standard error,Number of sources,Lower CI,Upper CI,...,Freedom House Nations in Transit,Global Insights Country Risk Ratings,IMD World Competitiveness Yearbook,PERC Asia Risk Guide,PRS International Country Risk Guide,Varieties of Democracy Project,World Bank CPIA,World Economic Forum EOS,World Justice Project Rule of Law Index,Transparency International Bribe Payers Survey
0,Afghanistan,AFG,2012,AP,8,174,3.30,3,2,13,...,NaN,1.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN
1,Afghanistan,AFG,2013,AP,8,175,3.30,3,3,13,...,NaN,1.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN
2,Afghanistan,AFG,2014,AP,12,172,1.29,4,10,14,...,NaN,11.0,NaN,NaN,NaN,NaN,12.0,NaN,16.0,NaN
3,Afghanistan,AFG,2015,AP,11,166,3.49,4,5,17,...,NaN,11.0,NaN,NaN,NaN,NaN,12.0,NaN,2.0,NaN
4,Afghanistan,AFG,2016,AP,15,169,1.74,5,12,17,...,NaN,10.0,NaN,NaN,NaN,16.0,13.0,NaN,13.0,NaN

In [94]:
epi14_data.columns

Index(['Rank', 'ISO3v10', 'Country', '2014 EPI Score',
       '10-Year Percent Change', 'Environmental Health', 'Ecosystem Vitality',
       'EH - Health Impacts', 'EH - Air Quality', 'EH -Water and Sanitation',
       'EV - Water Resources', 'EV - Agriculture', 'EV - Forests',
       'EV - Fisheries', 'EV- Biodiversity and Habitat',
       'EV - Climate and Energy', 'Child Mortality', 'Household Air Quality',
       'Air Pollution - Average Exposure to PM2.5',
       'Air Pollution - Average PM2.5 Exceedance', 'Access to Sanitation',
       'Access to Drinking Water', 'Wastewater Treatment',
       'Agricultural Subsidies', 'Pesticide Regulation',
       'Change in Forest Cover ', 'Fish Stocks',
       'Coastal Shelf Fishing Pressure',
       'Terrestrial Protected Areas (National Biome Weights)',
       'Terrestrial Protected Areas (Global Biome Weights)',
       'Marine Protected Areas', 'Critical Habitat Protection',
       'Trend in Carbon Intensity', 'Change of Trend in Carbon Intensity',
       'Trend in CO2 Emissions per KwH', 'Access to Electricity'],
      dtype='object')

In [95]:
epi16_data.columns

Index(['Rank', 'Country', 'ISO3', '2016 EPI Score', '10-Year Percent Change',
       'Environmental Health', 'Ecosystem Vitality', 'EH - Health Impacts',
       'EH - Air Quality', 'EH - Water and Sanitation', 'EV - Water Resources',
       'EV - Agriculture', 'EV - Forests', 'EV - Fisheries',
       'EV - Biodiversity and Habitat', 'EV - Climate and Energy',
       'Environmental Risk Exposure', 'Household Air Quality',
       'Household Air Quality - Risk Exposure',
       'Air Pollution - Average Exposure to PM2.5',
       'Air Pollution - Average Exposure to PM2.5 - Risk Exposure',
       'Air Pollution - Average PM2.5 Exceedance',
       'Air Pollution - Average Exposure to NO2', 'Access to Sanitation',
       'Unsafe Sanitation- Risk Exposure', 'Access to Drinking Water',
       'Unsafe Drinking Water Quality -Risk Exposure', 'Wastewater Treatment',
       'Nitrogen Use Efficiency', 'Nitrogen Balance', 'Tree Cover Loss',
       'Fish Stocks', 'Terrestrial Protected Areas (National Biome Weights)',
       'Terrestrial Protected Areas (Global Biome Weights)',
       'Marine Protected Areas', 'Species Protection (National)',
       'Species Protection (Global)', 'Trend in Carbon Intensity',
       'Trend in CO2 Emissions per KwH', 'Access to Electricity'],
      dtype='object')

In [96]:
epi18_data.columns

Index(['code', 'iso', 'country', 'EPI.current', 'HLT.current', 'AIR.current',
       'H2O.current', 'HMT.current', 'ECO.current', 'BDH.current',
       'FOR.current', 'FSH.current', 'CCE.current', 'APE.current',
       'WRS.current', 'AGR.current', 'HAD.current', 'PME.current',
       'PMW.current', 'USD.current', 'UWD.current', 'PBD.current',
       'MPA.current', 'TBN.current', 'TBG.current', 'SPI.current',
       'PAR.current', 'SHI.current', 'TCL.current', 'FSS.current',
       'MTR.current', 'DCT.current', 'DPT.current', 'DMT.current',
       'DNT.current', 'DBT.current', 'DST.current', 'DXT.current',
       'WWT.current', 'SNM.current'],
      dtype='object')

In [97]:
epi20_data.columns

Index(['code', 'iso', 'country', 'EPI.new', 'HLT.new', 'AIR.new', 'PMD.new',
       'HAD.new', 'OZD.new', 'H2O.new',
       ...
       'LCB.rnk.new', 'GIB.rnk.new', 'GHP.rnk.new', 'APE.rnk.new',
       'SDA.rnk.new', 'NXA.rnk.new', 'AGR.rnk.new', 'SNM.rnk.new',
       'WRS.rnk.new', 'WWT.rnk.new'],
      dtype='object', length=141)

In [98]:
epi22_data.columns

Index(['code', 'iso', 'country', 'region', 'EPI.new', 'HLT.new', 'AIR.new',
       'HAD.new', 'PMD.new', 'OZD.new',
       ...
       'CCH.rnk.old', 'CDA.rnk.old', 'CHA.rnk.old', 'FGA.rnk.old',
       'NDA.rnk.old', 'BCA.rnk.old', 'GHN.rnk.old', 'LCB.rnk.old',
       'GIB.rnk.old', 'GHP.rnk.old'],
      dtype='object', length=279)

In [99]:
epi24_data.columns

Index(['code', 'iso', 'country', 'EPI.old', 'EPI.new', 'ECO.old', 'ECO.new',
       'BDH.old', 'BDH.new', 'MKP.old',
       ...
       'LUF.old', 'LUF.new', 'GTI.old', 'GTI.new', 'GTP.old', 'GTP.new',
       'GHN.old', 'GHN.new', 'CBP.old', 'CBP.new'],
      dtype='object', length=149)

EPI PROCESSING

In [100]:
# Create a new dataframe for each year with only the country and EPI score, and add a year column for comparison in final_df
# 2014
epi14 = epi14_data[['Country', '2014 EPI Score']].copy()
epi14.columns = ['Country', 'EPI_Score']
epi14['Year'] = 2014

# 2016
epi16 = epi16_data[['Country', '2016 EPI Score']].copy()
epi16.columns = ['Country', 'EPI_Score']
epi16['Year'] = 2016

# 2018
epi18 = epi18_data[['country', 'EPI.current']].copy()
epi18.columns = ['Country', 'EPI_Score']
epi18['Year'] = 2018

# 2020
epi20 = epi20_data[['country', 'EPI.new']].copy()
epi20.columns = ['Country', 'EPI_Score']
epi20['Year'] = 2020

# 2022 
epi22 = epi22_data[['country', 'EPI.new']].copy()
epi22.columns = ['Country', 'EPI_Score']
epi22['Year'] = 2022

# 2024 
epi24 = epi24_data[['country', 'EPI.new']].copy()
epi24.columns = ['Country', 'EPI_Score']
epi24['Year'] = 2024

In [101]:
# Merge all EPI dfs into single df
epi_dfs = pd.concat([epi14, epi16, epi18, epi20, epi22, epi24], ignore_index=True)
print(epi_dfs[epi_dfs['Country'] == 'United States of America'])

                       Country  EPI_Score  Year
32    United States of America      67.52  2014
203   United States of America      84.72  2016
530   United States of America      71.19  2018
708   United States of America      69.30  2020
888   United States of America      51.10  2022
1070  United States of America      57.20  2024

CPI PROCESSING

In [102]:
cpi_df = cpi_data.copy()
cpi_df.head()

,Country / Territory,ISO3,Year,Region,CPI score,Rank,Standard error,Number of sources,Lower CI,Upper CI,...,Freedom House Nations in Transit,Global Insights Country Risk Ratings,IMD World Competitiveness Yearbook,PERC Asia Risk Guide,PRS International Country Risk Guide,Varieties of Democracy Project,World Bank CPIA,World Economic Forum EOS,World Justice Project Rule of Law Index,Transparency International Bribe Payers Survey
0,Afghanistan,AFG,2012,AP,8,174,3.30,3,2,13,...,NaN,1.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN
1,Afghanistan,AFG,2013,AP,8,175,3.30,3,3,13,...,NaN,1.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN
2,Afghanistan,AFG,2014,AP,12,172,1.29,4,10,14,...,NaN,11.0,NaN,NaN,NaN,NaN,12.0,NaN,16.0,NaN
3,Afghanistan,AFG,2015,AP,11,166,3.49,4,5,17,...,NaN,11.0,NaN,NaN,NaN,NaN,12.0,NaN,2.0,NaN
4,Afghanistan,AFG,2016,AP,15,169,1.74,5,12,17,...,NaN,10.0,NaN,NaN,NaN,16.0,13.0,NaN,13.0,NaN

In [103]:
# Look at null percentages for each column in cpi_df to determine which variables to use
null_percentages = (cpi_df.isnull().sum() / len(cpi_df)) * 100
print(null_percentages)

Country / Territory                                     0.000000
ISO3                                                    0.000000
Year                                                    0.000000
Region                                                  0.000000
CPI score                                               0.000000
Rank                                                    0.000000
Standard error                                          0.000000
Number of sources                                       0.000000
Lower CI                                                0.000000
Upper CI                                                0.000000
African Development Bank CPIA                          76.182839
Bertelsmann Foundation Sustainable Governance Index    78.267843
Bertelsmann Foundation Transformation Index            25.380914
Economist Intelligence Unit Country Ratings            25.942261
Freedom House Nations in Transit                       83.720930
Global Insights Country Risk Ratings                    0.360866
IMD World Competitiveness Yearbook                     64.795509
PERC Asia Risk Guide                                   91.539695
PRS International Country Risk Guide                   21.531676
Varieties of Democracy Project                         34.322374
World Bank CPIA                                        61.788292
World Economic Forum EOS                               26.864475
World Justice Project Rule of Law Index                33.279872
Transparency International Bribe Payers Survey         97.674419
dtype: float64

In [104]:
# Drop all columns with more than 35% null values
columns_to_drop = null_percentages[null_percentages > 35].index
cpi_df = cpi_df.drop(columns=columns_to_drop , errors='ignore')

In [105]:
null_percentages_after_drop = (cpi_df.isnull().sum() / len(cpi_df)) * 100
print(null_percentages_after_drop)

Country / Territory                             0.000000
ISO3                                            0.000000
Year                                            0.000000
Region                                          0.000000
CPI score                                       0.000000
Rank                                            0.000000
Standard error                                  0.000000
Number of sources                               0.000000
Lower CI                                        0.000000
Upper CI                                        0.000000
Bertelsmann Foundation Transformation Index    25.380914
Economist Intelligence Unit Country Ratings    25.942261
Global Insights Country Risk Ratings            0.360866
PRS International Country Risk Guide           21.531676
Varieties of Democracy Project                 34.322374
World Economic Forum EOS                       26.864475
World Justice Project Rule of Law Index        33.279872
dtype: float64

FINAL MERGE

In [106]:
cpi_df = cpi_df.rename(columns={'Country / Territory': 'Country'})

final_df = pd.merge(epi_dfs, cpi_df, left_on=['Country', 'Year'], right_on=['Country', 'Year'], how='inner')
final_df.head()

,Country,EPI_Score,Year,ISO3,Region,CPI score,Rank,Standard error,Number of sources,Lower CI,Upper CI,Bertelsmann Foundation Transformation Index,Economist Intelligence Unit Country Ratings,Global Insights Country Risk Ratings,PRS International Country Risk Guide,Varieties of Democracy Project,World Economic Forum EOS,World Justice Project Rule of Law Index
0,Switzerland,87.67,2014,CHE,WE/EU,86,5,2.61,6,82,90,NaN,88.0,73.0,89.0,NaN,86.0,NaN
1,Luxembourg,83.29,2014,LUX,WE/EU,82,9,2.78,6,77,87,NaN,71.0,83.0,89.0,NaN,90.0,NaN
2,Australia,82.40,2014,AUS,AP,80,11,1.31,8,78,82,NaN,71.0,83.0,79.0,NaN,83.0,80.0
3,Singapore,81.78,2014,SGP,AP,84,7,1.75,8,81,87,75.0,88.0,83.0,79.0,NaN,90.0,84.0
4,Germany,80.47,2014,DEU,WE/EU,79,12,2.58,7,75,83,NaN,88.0,73.0,89.0,NaN,75.0,76.0

In [107]:
# Drop columns that are irrelevant
columns_to_drop_final = ['ISO3', 'Rank', 'Number of sources']
final_df = final_df.drop(columns=columns_to_drop_final, errors='ignore')
final_df.head()

,Country,EPI_Score,Year,Region,CPI score,Standard error,Lower CI,Upper CI,Bertelsmann Foundation Transformation Index,Economist Intelligence Unit Country Ratings,Global Insights Country Risk Ratings,PRS International Country Risk Guide,Varieties of Democracy Project,World Economic Forum EOS,World Justice Project Rule of Law Index
0,Switzerland,87.67,2014,WE/EU,86,2.61,82,90,NaN,88.0,73.0,89.0,NaN,86.0,NaN
1,Luxembourg,83.29,2014,WE/EU,82,2.78,77,87,NaN,71.0,83.0,89.0,NaN,90.0,NaN
2,Australia,82.40,2014,AP,80,1.31,78,82,NaN,71.0,83.0,79.0,NaN,83.0,80.0
3,Singapore,81.78,2014,AP,84,1.75,81,87,75.0,88.0,83.0,79.0,NaN,90.0,84.0
4,Germany,80.47,2014,WE/EU,79,2.58,75,83,NaN,88.0,73.0,89.0,NaN,75.0,76.0